-- GridShift AI
-- Load the five CSV files after uploading them to @GRIDSHIFT_STAGE.
-- In Snowsight, open Data > Add Data > Load files into a stage,
-- select GRIDSHIFT_DB.CORE.GRIDSHIFT_STAGE, and upload the CSV files.

USE WAREHOUSE GRIDSHIFT_WH;
USE DATABASE GRIDSHIFT_DB;
USE SCHEMA CORE;

LIST @GRIDSHIFT_STAGE;

TRUNCATE TABLE AI_WORKLOADS;
TRUNCATE TABLE ELECTRICITY_TARIFFS;
TRUNCATE TABLE RENEWABLE_AVAILABILITY;
TRUNCATE TABLE GRID_CONDITIONS;
TRUNCATE TABLE COMPUTE_CAPACITY;

COPY INTO AI_WORKLOADS
FROM @GRIDSHIFT_STAGE/ai_workloads.csv
FILE_FORMAT = (FORMAT_NAME = GRIDSHIFT_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

COPY INTO ELECTRICITY_TARIFFS
FROM @GRIDSHIFT_STAGE/electricity_tariffs.csv
FILE_FORMAT = (FORMAT_NAME = GRIDSHIFT_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

COPY INTO RENEWABLE_AVAILABILITY
FROM @GRIDSHIFT_STAGE/renewable_availability.csv
FILE_FORMAT = (FORMAT_NAME = GRIDSHIFT_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

COPY INTO GRID_CONDITIONS
FROM @GRIDSHIFT_STAGE/grid_conditions.csv
FILE_FORMAT = (FORMAT_NAME = GRIDSHIFT_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

COPY INTO COMPUTE_CAPACITY
FROM @GRIDSHIFT_STAGE/compute_capacity.csv
FILE_FORMAT = (FORMAT_NAME = GRIDSHIFT_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

SELECT 'AI_WORKLOADS' AS table_name, COUNT(*) AS row_count FROM AI_WORKLOADS
UNION ALL
SELECT 'ELECTRICITY_TARIFFS', COUNT(*) FROM ELECTRICITY_TARIFFS
UNION ALL
SELECT 'RENEWABLE_AVAILABILITY', COUNT(*) FROM RENEWABLE_AVAILABILITY
UNION ALL
SELECT 'GRID_CONDITIONS', COUNT(*) FROM GRID_CONDITIONS
UNION ALL
SELECT 'COMPUTE_CAPACITY', COUNT(*) FROM COMPUTE_CAPACITY
ORDER BY table_name;

SELECT
    MIN(timestamp) AS period_start,
    MAX(timestamp) AS period_end,
    COUNT(*) AS hourly_rows
FROM HOURLY_ENERGY_CONTEXT;

SELECT
    flexibility_level,
    COUNT(*) AS workload_count,
    SUM(duration_hours) AS total_duration_hours,
    SUM(power_requirement_kw * duration_hours) AS estimated_energy_kwh
FROM AI_WORKLOADS
GROUP BY flexibility_level
ORDER BY flexibility_level;
